id = "csharp-language-server"
name = "csharp-ls"
description = "Roslyn-based LSP language server for C#."
homepage = "https://docs.astral.sh/ty"
licenses = ["MIT"]
categories = ["LSP"]

[source]
id = "pkg:nuget/csharp-ls@0.19.0"

[bin]
csharp-ls = "nuget:csharp-ls"
