id = "basedpyright"
name = "Basedpyright"
languages = [
  "python",
]
package = "basedpyright"
command = [
  "basedpyright-langserver",
  "--stdio",
]
root_markers = [
  "pyproject.toml",
  "setup.py",
  "setup.cfg",
  "requirements.txt",
  "Pipfile",
  "pyrightconfig.json",
]
