id = "clangd"
name = "clangd"
languages = [
  "c",
  "cpp",
  "objc",
  "objcpp",
]
package = "clangd"
command = [
  "clangd",
]
root_markers = [
  ".clangd",
  ".clang-tidy",
  ".clang-format",
  "compile_commands.json",
  "compile_flags.txt",
  "configure.ac",
]
