id = "json-lsp"
name = "JSON Language Server"
languages = [ "json" ]
package = "json-lsp"
command = [ "vscode-json-language-server", "--stdio" ]
root_markers = [ "package.json" ]
extensions_replaceable = [ "apexskier.json" ]
