id = "phpactor"
name = "phpactor"
languages = [ "php" ]
package = "phpactor"
command = [ "phpactor", "language-server" ]
root_markers = [
  "composer.json",
  ".phpactor.json",
  ".phpactor.yml",
]
extensions_replaceable = [ "emran-mr.phpactor" ]
