id = "sourcekit-lsp"
name = "SourceKit-LSP"
languages = [
  "swift",
  "c",
  "cpp",
  "objc",
  "objcpp",
]
command = [ "sourcekit-lsp" ]
root_markers = [
  "buildServer.json",
  "compile_commands.json",
  "compile_flags.txt",
  "Package.swift",
  "*.xcodeproj",
  "*.xcworkspace",
]
extensions_replaceable = [ "panic.Icarus" ]
