id = "typescript-language-server"
name = "TypeScript Language Server"
languages = [
  "javascript",
  "typescript",
  "tsx",
]
package = "typescript-language-server"
command = [ "typescript-language-server", "--stdio" ]
root_markers = [
  "jsconfig.json",
  "tsconfig.json",
  "package.json",
]
