id = "vtsls"
name = "vtsls"
languages = [
  "javascript",
  "typescript",
  "tsx",
]
package = "vtsls"
command = [ "vtsls", "--stdio" ]
root_markers = [
  "jsconfig.json",
  "tsconfig.json",
  "package.json",
]
