id = "basedpyright"
name = "Basedpyright"
description = "Fork of the Pyright static type checker for Python, with extra Pylance features."
homepage = "https://docs.basedpyright.com"
licenses = ["MIT"]
categories = ["LSP"]

[source]
id = "pkg:pypi/basedpyright@1.38.3"

[bin]
basedpyright = "pypi:basedpyright"
basedpyright-langserver = "pypi:basedpyright-langserver"
