id = "docker-language-server"
name = "Docker Language Server"
description = "Language server for Dockerfiles, Compose files, and Bake files."
homepage = "https://github.com/docker/docker-language-server"
licenses = ["MIT"]
categories = ["LSP"]

[source]
id = "pkg:github/docker/docker-language-server@v0.20.1"

[[source.asset]]
target = "darwin_arm64"
file = "docker-language-server-darwin-arm64-{{version}}"

[[source.asset]]
target = "darwin_x64"
file = "docker-language-server-darwin-amd64-{{version}}"

[bin]
docker-language-server = "{{source.asset.file}}"
