id = "lua-language-server"
name = "Lua Language Server"
description = "A language server that offers Lua language support - programmed in Lua."
homepage = "https://github.com/LuaLS/lua-language-server"
licenses = ["MIT"]
categories = ["LSP"]

[source]
id = "pkg:github/LuaLS/lua-language-server@3.17.1"

[[source.asset]]
target = "darwin_arm64"
file = "lua-language-server-{{version}}-darwin-arm64.tar.gz:libexec/"
bin = "exec:libexec/bin/lua-language-server"

[[source.asset]]
target = "darwin_x64"
file = "lua-language-server-{{version}}-darwin-x64.tar.gz:libexec/"
bin = "exec:libexec/bin/lua-language-server"

[bin]
lua-language-server = "{{source.asset.bin}}"
