id = "marksman"
name = "marksman"
description = "Markdown LSP server providing completion, cross-references, diagnostics, and more."
homepage = "https://github.com/artempyanykh/marksman"
licenses = ["MIT"]
categories = ["LSP"]

[source]
# renovate:versioning=loose
id = "pkg:github/artempyanykh/marksman@2024-12-18"

[[source.asset]]
target = "darwin"
file = "marksman-macos"

[bin]
marksman = "{{source.asset.file}}"
