id = "phpactor"
name = "Phpactor"
description = "A PHP Language Server with more features than you can shake a stick at."
homepage = "https://phpactor.readthedocs.io"
licenses = ["MIT"]
categories = ["LSP"]

[source]
# renovate:versioning=loose
id = "pkg:github/phpactor/phpactor@2025.12.21.1"

[source.asset]
file = "phpactor.phar"

[bin]
phpactor = "php:phpactor.phar"
