id = "ruby-lsp"
name = "Ruby LSP"
description = "An opinionated language server for Ruby."
homepage = "https://github.com/Shopify/ruby-lsp"
licenses = ["MIT"]
categories = ["LSP"]

[source]
id = "pkg:gem/ruby-lsp@0.26.8"
extra_packages = ["ruby-lsp-rails"]

[bin]
ruby-lsp = "gem:ruby-lsp"
