id = "rust-analyzer"
name = "rust-analyzer"
description = "An implementation of the Language Server Protocol for the Rust programming language."
homepage = "https://github.com/rust-lang/rust-analyzer"
licenses = ["Apache-2.0", "MIT"]
categories = ["LSP"]

[source]
# renovate:versioning=loose
id = "pkg:github/rust-lang/rust-analyzer@2026-03-23"

[[source.asset]]
target = "darwin_arm64"
file = "rust-analyzer-aarch64-apple-darwin.gz"
bin = "rust-analyzer-aarch64-apple-darwin"

[[source.asset]]
target = "darwin_x64"
file = "rust-analyzer-x86_64-apple-darwin.gz"
bin = "rust-analyzer-x86_64-apple-darwin"

[bin]
rust-analyzer = "{{source.asset.bin}}"
