id = "solargraph"
name = "Solargraph"
description = "A Ruby language server."
homepage = "https://solargraph.org"
licenses = ["MIT"]
categories = ["LSP"]

[source]
id = "pkg:gem/solargraph@0.58.3"

[bin]
solargraph = "gem:solargraph"
