id = "vtsls"
name = "vtsls"
description = "A wrapper around the TypeScript service from Microsoft."
homepage = "https://github.com/yioneko/vtsls"
licenses = ["MIT"]
categories = ["LSP"]

[source]
id = "pkg:npm/%40vtsls/language-server@0.2.9"

[bin]
vtsls = "npm:vtsls"
