---
name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: panicinc/nova-actions/registry-release@v1
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.CDN_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.CDN_ACCESS_SECRET }}
