---
id: solargraph
name: Solargraph
description: A Ruby language server.
homepage: https://solargraph.org
licenses:
  - MIT
languages:
  - Ruby
categories:
  - LSP

source:
  id: pkg:gem/solargraph@0.56.2

bin:
  solargraph: gem:solargraph
